### ISSUE TITLE
Got ERROR: Failed to download minimal PHP for bootstrapping.

### ISSUE THREAD

**Issue by sandinmyjoints** [swg/dokku-ttrss#1]
On first deploy, this is what I got:

```
$ git push dokku master
Pseudo-terminal will not be allocated because stdin is not a terminal.
Enumerating objects: 26, done.
Counting objects: 100% (26/26), done.
Delta compression using up to 4 threads
Compressing objects: 100% (23/23), done.
Writing objects: 100% (26/26), 9.33 KiB | 2.33 MiB/s, done.
Total 26 (delta 8), reused 0 (delta 0)
-----> Cleaning up...
-----> Building dokku-ttrss from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> PHP app detected
-----> Bootstrapping...
       
       !     ERROR: Failed to download minimal PHP for bootstrapping.
       Please try again, or contact support if this problem persists.
       
To dokku:dokku-ttrss
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku:dokku-ttrss'
```

I'm wondering if something in the Dockerfile is outdated, maybe relying on a deprecated dependency? Any ideas?

**Comment by sandinmyjoints** [comment]
This persisted after I did a `dokku-update`.

**Comment by swg** [comment]
I was able to reproduce this at first, but I went ahead and did a dist-upgrade on my server and it now bootstraps correctly. Try upgrading your herokuish and docker versions again, or you could also try setting your buildpack version manually:

`dokku config:set ttrss BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git#v148`

Followed by `dokku ps:rebuild ttrss` or `git push`

**Comment by swg** [comment]
Added some notes to the README for these errors in 63980c32f352acb4dfd040cd940b669b8a5bb568 and 359d5fb72eb97f725b09a864df3aa275ed3ea70b when I was adding support for git plugins. Closing.
